name: Generate and Save Keystore

on: 
  workflow_dispatch: # This allows you to run it manually from the Actions tab

jobs:
  create-keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Generate Keystore File
        run: |
          keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "C=US, O=Android, CN=Android Debug"

      - name: Commit Keystore to Repo
        run: |
          git config --global user.name "ZBro7-Bot"
          git config --global user.email "bot@soccerlegacy.com"
          git add debug.keystore
          git commit -m "Add permanent debug keystore"
          git push
